Root:
  XilinxZcu216:
    Application:
    Application:
      AppRingBuffer:
        Adc:
          Ch[0]:
            TrigBurst: 0x0
            ContinuousMode: 0x1
        Dac:
          Ch[0]:
            TrigBurst: 0x0
            ContinuousMode: 0x1
      DacSigGen:
        enable: True
        Enabled: 0x1
        Continuous: 0x1
        # CsvFilePath: 'config/DacSigGen/1tone_10_5MHz.csv'
        # CsvFilePath: 'config/DacSigGen/1tone_500MHz.csv'
        # CsvFilePath: 'config/DacSigGen/2tone_500MHz_500kHzspacing.csv'
        CsvFilePath: 'config/DacSigGen/Ntone_1GHz_blanksection.csv'
